language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run
  - ./vendor/bin/phpunit --testdox

notifications:
  - email: false